version: 2
updates:
  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Cargo
  - package-ecosystem: "cargo"
    directory: "/pkg"
    schedule:
      interval: "weekly"
