language: go
cache:
  directories:
    - $GOCACHE
    - $GOPATH/pkg/mod
sudo: required
go:
  - "1.12.x"
  - "1.13.x"
jobs:
  include:
    - stage: Build
      script: make build
    - stage: Test
      script: make test
      name: Install
    - script: make install