name: Build

on: [push, pull_request]


jobs:
  setup-build-test:
    name: Setup, Build, Test
    strategy:
      matrix:
        go-version: [1.12.x]
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build
      run: brew install ffmpeg && make