name: CI

on: [push, pull_request]


jobs:
  setup-build-test:
    name: Setup, Build, Test
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x]
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v -coverage ./...
    - name: Build
      run: make all
