name: release new binaries

on:
  workflow_dispatch:
    inputs:
      reason:
        description: new release message
        required: true
  push:
    tags:
      - "*"

permissions:
  contents: write


jobs:
  publish-go-package-on-release:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
