# Run security audit
# Author: Nyah Check
name: Run Security Audit

on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  run-security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions-rs/audit-check@v1
        with:
          path: ./pkg/download
          token: ${{ secrets.GITHUB_TOKEN }}
